name: Ruby on Rails CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rails test
        env:
          RAILS_ENV: test
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
          GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run asset precompilation
        run: bundle exec rake assets:precompile
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 395776234152.dkr.ecr.us-east-2.amazonaws.com/weatherapp:latest

      - name: Set up kubectl
        run: echo ${{ secrets.KUBECONFIG }} | base64 --decode > $GITHUB_WORKSPACE/.kubeconfig

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8/deployment.yaml -n default --kubeconfig $GITHUB_WORKSPACE/.kubeconfig
          kubectl apply -f k8/ingress.yaml -n default --kubeconfig $GITHUB_WORKSPACE/.kubeconfig

      - name: Deploy to Kubernetes
        run: kubectl set image deployment/weatherapp weatherapp=395776234152.dkr.ecr.us-east-2.amazonaws.com/weatherapp:latest -n default --kubeconfig $GITHUB_WORKSPACE/.kubeconfig